#!/usr/bin/env bash

shopt -s autocd
shopt -s checkwinsize
export HISTFILESIZE=10000
export HISTCONTROL=ignoreboth

#show colored man-pages
export LESS_TERMCAP_mb=$'\E[01;31m'
export LESS_TERMCAP_md=$'\E[01;36m'
export LESS_TERMCAP_me=$'\E[0m'
export LESS_TERMCAP_se=$'\E[0m'
export LESS_TERMCAP_so=$'\E[01;44;33m'
export LESS_TERMCAP_ue=$'\E[0m'
export LESS_TERMCAP_us=$'\E[01;32m'

# nmtui theme
export NEWT_COLORS='root=black,black;window=black,black;border=white,black;listbox=white,black;label=blue,black;checkbox=red,black;title=green,black;button=white,red;actsellistbox=white,red;actlistbox=white,gray;compactbutton=white,gray;actcheckbox=white,blue;entry=lightgray,black;textbox=blue,black'

alias reload=". ~/.bashrc"

# Bind PageUp and PageDown to history search
if [ -n "$BASH_VERSION" -a -n "$PS1" ]; then
	bind '"\e[5~": history-search-backward'
	bind '"\e[6~": history-search-forward'
fi

source ~/.profile.d/load
